image_to_json_task:
  description: >
    Convert the image data to json {image}
    Make sure you have the date from the uploaded image {bill_date}.
  expected_output: >
    A json file from the bill in the {image}
  agent: image_to_json_convertor

inventory_managing_task:
  description: >
    Take the context you got and update the inventory as a json file.
    Make sure the inventory has the date you found from the context.
  expected_output: >
    A json file with the inventory
  agent: inventory_manager

snapshot_managering_task:
  description: >
    Take the inventory json file and predict the current availability based on the usage pattern and write it in a json file
  expected_output: >
    A json file with the current snapshop
  agent: snapshot_manager

shopping_recommendation_task:
  description: >
    When propted by the user, use the json file with the current snapshop to determine the shopping recommendation on the day
  expected_output: >
    A json file with the shopping recommendation
  agent: shopping_recommender
